server:
  port: 8090
  servlet:
    context-path: /api

spring:
  jackson:
    # 返回json数据时屏蔽null数据
    default-property-inclusion: non_null
  datasource:
    username: root
    password: 456456asd
    url: jdbc:mysql://localhost:3306/yangtuo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    # 配置获取连接等待超时的时间
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initiaSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictablIdleTimeMills: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

mybatis:
  # 配置mapper存放位置
  mapper-locations: classpath:mapper/*.xml
  # 配置别名
  type-aliases-package: me.neoyang.yangtuoserver.bean
  # 打印SQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    lazy-loading-enabled: true
    #false 为按需加载
    aggressive-lazy-loading: false


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0

#showSql
logging:
  level:
    me:
      neoyang:
        yangtuoserver:
          dao: DEBUG

